Build work for SSL 0.9.8 support as well as SSL 1.0.0 support

diff --git a/build/configure b/build/configure
--- a/build/configure
+++ b/build/configure
@@ -49,7 +49,7 @@ fi
 
 gcc_compiler_bug_18251_resolved() {
     # POSIX Semantic Version <= Test
-    # Exit code 0 is success (i.e. true), meaning optimization is necessary
+    # Exit code 0 is failure (i.e. false), meaning we still have the bug
     #
     # Parameter: "x.y.z" (like "4.2.2"), for major.minor.patch versions
 
@@ -57,38 +57,45 @@ gcc_compiler_bug_18251_resolved() {
     local MAJOR=`echo $1 | cut -d. -f1`
     local MINOR=`echo $1 | cut -d. -f2`
     local PATCH=`echo $1 | cut -d. -f3`
+    local DATE=$2
 
     # Version with the compiler bug
     local TEST_MAJOR=4
     local TEST_MINOR=1
     local TEST_PATCH=2
+    local TEST_DATE=20070525
 
     # Check bounds on MAJOR
     if [ $MAJOR -lt $TEST_MAJOR ]; then
-	return 0
+        return 0
     elif [ $MAJOR -gt $TEST_MAJOR ]; then
-	return 1
+        return 1
     fi
 
     # MAJOR matched, so check bounds on MINOR
     if [ $MINOR -lt $TEST_MINOR ]; then
-	return 0
+        return 0
     elif [ $MINOR -gt $TEST_MINOR ]; then
-	return 1
+        return 1
     fi
 
     # MINOR matched, so check bounds on PATCH
     if [ $PATCH -lt $TEST_PATCH ]; then
-	return 0
+        return 0
     elif [ $PATCH -gt $TEST_PATCH ]; then
-	return 1
+        return 1
     fi
 
-    # PATCH matched, so it is equal
-    return 0
+    # What about the build date?
+    if [ $DATE -lt $TEST_DATE ]; then
+        return 0
+    fi
+
+    # GCC version includes fix for compiler bug
+    return 1
 }
 
-GCC_VERSION=`g++ --version | head -1 | awk '{print $3}'`
+GCC_VERSION=`g++ --version | head -1 | awk '{print $3, $4}'`
 
 gcc_compiler_bug_18251_resolved $GCC_VERSION
 if [ $? -eq 0 ]; then
@@ -196,14 +203,14 @@ if [ "$opensource_distro" -eq 1 ]; then
     NOULINUX=1
 fi
 
-# See if we're running on a Ubuntu 12 (universal) system; if so, assume ULINUX
+# See if we're running on a CentOS 5.1 or RedHat 5.1 (universal) system; if so, assume ULINUX
 
 if [ "$NOULINUX" != "1" ]; then
-    if [ -e /etc/lsb-release -a -d /usr/local_ssl_1.0.0 ]; then 
-        . /etc/lsb-release
-        PF_MAJOR=`echo $DISTRIB_RELEASE | cut -d= -f2 | cut -d. -f1`
-        PF_MINOR=`echo $DISTRIB_RELEASE | cut -d= -f2 | cut -d. -f2`
-        if [ "$PF_MAJOR" -eq "12" -a "$PF_MINOR" -eq "4" ]; then
+    if [ -e /etc/redhat-release -a -d /usr/local_ssl_0.9.8 -a -d /usr/local_ssl_1.0.0 ]; then 
+        PF_MAJOR=`head -n 1 /etc/redhat-release | sed 's/.* \([0-9][0-9]*\)[ \.].*/\1/'`
+        PF_MINOR=`(head -n 1 /etc/redhat-release | sed 's/.* [0-9][0-9]*[\.]\([0-9][0-9]*\).*/\1/') | grep -v '[^0-9]' || echo '0'`
+        # Note: CentOS 5.1 identifies itself as CentOS 5
+        if [ "$PF_MAJOR" -eq "5" -a "$PF_MINOR" -eq "0" ]; then
             ULINUX=1
         fi
     fi
@@ -211,9 +218,11 @@ fi
 
 # And we need our local SSL directories to be able to deal with ULINUX
 
-if [ $ULINUX -eq 1 -a ! -d /usr/local_ssl_1.0.0 ]; then
-    echo "Missing /usr/local_ssl_* directories to build a ULINUX kit" >& 2
-    exit 1
+if [ $ULINUX -eq 1 ]; then
+    if [ ! -d /usr/local_ssl_0.9.8 -o ! -d /usr/local_ssl_1.0.0 ]; then
+        echo "Missing /usr/local_ssl_* directories to build a ULINUX kit" >& 2
+        exit 1
+    fi
 fi
 
 # Note: Most of this code came from the PAL configure file
@@ -270,14 +279,7 @@ case $uname in
         elif [ -n "$CHECK_CENTOS" ]; then
             PF_MAJOR=`head -n 1 /etc/redhat-release | sed 's/.* \([0-9][0-9]*\)[ \.].*/\1/'`
             PF_MINOR=`(head -n 1 /etc/redhat-release | sed 's/.* [0-9][0-9]*[\.]\([0-9][0-9]*\).*/\1/') | grep -v '[^0-9]' || echo '0'`
-            if [ $PF_MAJOR -eq 5 -a $PF_MINOR -eq 0 ]; then
-                set_ulinux_pf
-                BUILD_RPM=1
-                BUILD_DPKG=1
-                ULINUX=1
-            else
-                PF_DISTRO=REDHAT
-            fi
+            PF_DISTRO=REDHAT
         elif [ -e /etc/lsb-release ]; then
             source /etc/lsb-release
             if [ "$DISTRIB_ID" = "Ubuntu" ]; then
@@ -340,20 +342,25 @@ fi
 
 ruby_configure_quals=(
     --disable-install-doc
+    --without-gmp
     --with-out-ext=${RUBY_EXTENSIONS}
     --prefix=/opt/microsoft/omsagent/ruby )
 
 if [ "$ULINUX" = "1" ]; then
-    ruby_configure_quals=(
-	\"LDFLAGS=-L /usr/local_ssl_1.0.0/${SSL_LIB_DIR} -Wl,-rpath=/opt/omi/lib\"
-	\"CPPFLAGS=-I /usr/local_ssl_1.0.0/include\"
-	${ruby_configure_quals[@]} )
+    ssl_098_dirpath=/usr/local_ssl_0.9.8
+    ruby_configure_quals_098=(
+        \"LDFLAGS=-L $ssl_098_dirpath/${SSL_LIB_DIR} -Wl,-rpath=/opt/omi/lib\"
+        \"CPPFLAGS=-I $ssl_098_dirpath/include\" )
+
+    ssl_100_dirpath=/usr/local_ssl_1.0.0
+    ruby_configure_quals_100=(
+        \"LDFLAGS=-L $ssl_100_dirpath/${SSL_LIB_DIR} -Wl,-rpath=/opt/omi/lib\"
+        \"CPPFLAGS=-I $ssl_100_dirpath/include\" )
 fi
 
 cat <<EOF > config.mak
 ENABLE_DEBUG=$enable_debug_flag
 OMI_CONFIGURE_QUALS="$omi_configure_quals"
-RUBY_CONFIGURE_QUALS=( ${ruby_configure_quals[@]} )
 
 BUILD_TYPE=$build_type
 PF=$PF
@@ -368,8 +375,16 @@ PF_DISTRO=$PF_DISTRO
 ULINUX=$ULINUX
 BUILD_CONFIGURATION=$BUILD_CONFIGURATION
 PACKAGE_SUFFIX=$PKG_SUFFIX
+
+RUBY_CONFIGURE_QUALS=( ${ruby_configure_quals[@]} )
 EOF
 
+if [ "$ULINUX" = "1" ]; then
+    echo "SSL_098_LIBPATH=${ssl_098_dirpath}/${SSL_LIB_DIR}" >> config.mak
+    echo "RUBY_CONFIGURE_QUALS_098=( ${ruby_configure_quals_098[@]} )" >> config.mak
+    echo "SSL_100_LIBPATH=${ssl_100_dirpath}/${SSL_LIB_DIR}" >> config.mak
+    echo "RUBY_CONFIGURE_QUALS_100=( ${ruby_configure_quals_100[@]} )" >> config.mak
+fi
 
 # Fix permissions in case they aren't executable - and then configure OMI
 chmod ug+x ${scxomi_dir}/configure ${scxomi_dir}/buildtool
