Use checked in version of bundler (rather than fetching it from the internet), and make other changes as necessary to support CentOS 5.0 as our build system..

diff --git a/build/configure b/build/configure
--- a/build/configure
+++ b/build/configure
@@ -18,7 +18,7 @@ NOULINIX=0
 omi_configure_quals=""
 
 if [ ! -d "$scxomi_dir" ]; then
-    echo "OMI directory ($scxomi_dir) does not exist"
+    echo "OMI directory ($scxomi_dir) does not exist" >& 2
     exit 1
 fi
 
@@ -26,11 +26,17 @@ fi
 # Ruby configuration qualifiers
 #
 
-# Some version of Ruby must be installed in order to build Ruby ...
+# Make sure we have the obvious build requirements for Ruby ...
 
 ruby -v 2>/dev/null 1>&2
 if [ $? -ne 0 ]; then
-    echo "Any version of Ruby must be installed in order to build Ruby"
+    echo "Any version of Ruby must be installed in order to build Ruby" >& 2
+    exit 1
+fi
+
+bison -V 2>/dev/null 1>&2
+if [ $? -ne 0 ]; then
+    echo "The bison program must be installed in order to build Ruby" >& 2
     exit 1
 fi
 
@@ -38,61 +44,27 @@ fi
 
 git --version 2>/dev/null 1>&2
 if [ $? -ne 0 ]; then
-    echo "Any version of git must be installed in order to build fluentd"
+    echo "Any version of git must be installed in order to build fluentd" >& 2
     exit 1
 fi
 
-# Note: Ruby has optimization issues with g++ v4.1.2 due to G++ bug # 18251:
-#   https://gcc.gnu.org/bugzilla/show_bug.cgi?id=18251
-
-perform_reduced_optimization() {
-    # POSIX Semantic Version <= Test
-    # Exit code 0 is success (i.e. true), meaning optimization is necessary
-    #
-    # Parameter: "x.y.z" (like "4.2.2"), for major.minor.patch versions
-
-    # Current version installed
-    local MAJOR=`echo $1 | cut -d. -f1`
-    local MINOR=`echo $1 | cut -d. -f2`
-    local PATCH=`echo $1 | cut -d. -f3`
-
-    # Version with the compiler bug
-    local TEST_MAJOR=4
-    local TEST_MINOR=1
-    local TEST_PATCH=2
-
-    # Check bounds on MAJOR
-    if [ $MAJOR -lt $TEST_MAJOR ]; then
-	return 0
-    elif [ $MAJOR -gt $TEST_MAJOR ]; then
-	return 1
-    fi
-
-    # MAJOR matched, so check bounds on MINOR
-    if [ $MINOR -lt $TEST_MINOR ]; then
-	return 0
-    elif [ $MINOR -gt $TEST_MINOR ]; then
-	return 1
-    fi
-
-    # MINOR matched, so check bounds on PATCH
-    if [ $PATCH -lt $TEST_PATCH ]; then
-	return 0
-    elif [ $PATCH -gt $TEST_PATCH ]; then
-	return 1
-    fi
-
-    # PATCH matched, so it is equal
-    return 0
-}
-
-RUBY_REDUCED_OPTIMIZATION=""
 GCC_VERSION=`g++ --version | head -1 | awk '{print $3}'`
 
-perform_reduced_optimization $GCC_VERSION
-if [ $? -eq 0 ]; then
-    RUBY_REDUCED_OPTIMIZATION="CFLAGS=-O1"
-fi   
+# Note: Ruby has optimization issues with g++ v4.1.2 pre-release due to G++ bug # 18251:
+#   https://gcc.gnu.org/bugzilla/show_bug.cgi?id=18251
+#
+# We can work around this via reduced optimization (see history of this file).
+# But rather than do that, we moved to a different platform with GCC v4.1.1
+# (which did not exhibit the problem).
+
+GCC_MAJOR=`echo $GCC_VERSION | cut -d. -f1`
+GCC_MINOR=`echo $GCC_VERSION | cut -d. -f2`
+GCC_PATCH=`echo $GCC_VERSION | cut -d. -f3`
+
+if [ $GCC_MAJOR -eq 4 -a $GCC_MINOR -eq 1 -a $GCC_PATCH -eq 2 ]; then
+    echo "Ruby can't compile with this version of GCC ($GCC_VERSION) due to compiler bug" >& 2
+    exit 1
+fi
 
 # List of ruby extensions. Disable everything, remove if:
 #   1. We absolutely need something, and
@@ -102,7 +74,7 @@ fi
 
 RUBY_EXTENSIONS="continuation,coverage,dbm,fiber,fiddle,gdbm,mathn,nkf,objspace,pty,racc,rbconfig,readline,ripper,sdbm,tk,win32,win32ole"
 
-ruby_configure_quals="--disable-install-doc ${RUBY_REDUCED_OPTIMIZATION} --with-out-ext=${RUBY_EXTENSIONS} --prefix=/opt/microsoft/omsagent/ruby"
+ruby_configure_quals="--disable-install-doc --with-out-ext=${RUBY_EXTENSIONS} --prefix=/opt/microsoft/omsagent/ruby"
 
 for opt
 do
@@ -123,11 +95,11 @@ do
 
     --enable-ulinux)
       if [ `uname` != "Linux" ]; then
-          echo "Cannot build for ULINUX on non-Linux platforms"
+          echo "Cannot build for ULINUX on non-Linux platforms" >& 2
           exit 1
       fi
       if [ "$NOULINUX" = "1" ]; then
-          echo "Conflicting qualifers: --enable-ulinux and --noenable-ulinux can't be specified together"
+          echo "Conflicting qualifers: --enable-ulinux and --noenable-ulinux can't be specified together" >& 2
           exit 1
       fi
       ULINUX=1
@@ -135,11 +107,11 @@ do
 
     --noenable-ulinux)
       if [ `uname` != "Linux" ]; then
-          echo "Cannot build for ULINUX on non-Linux platforms"
+          echo "Cannot build for ULINUX on non-Linux platforms" >& 2
           exit 1
       fi
       if [ "$ULINUX" = "1" ]; then
-          echo "Conflicting qualifers: --enable-ulinux and --noenable-ulinux can't be specified together"
+          echo "Conflicting qualifers: --enable-ulinux and --noenable-ulinux can't be specified together" >& 2
           exit 1
       fi
       NOULINUX=1
@@ -150,8 +122,8 @@ do
     ;;
 
     *)
-      echo "configure: invalid option '$opt'"
-      echo "Try configure --help' for more information."
+      echo "configure: invalid option '$opt'" >& 2
+      echo "Try configure --help' for more information." >& 2
       exit 1
     ;;
 
@@ -187,7 +159,7 @@ omi_configure_quals="${enable_debug} ${enable_omi_tools} ${omi_configure_quals}"
 pal_configure_quals="${enable_debug}"
 
 if [ "$ULINUX" -eq 1 -a "$opensource_distro" -eq 1 ]; then
-    echo "*** ULINUX not permitted for open source distributions; ULINUX disabled ***"
+    echo "*** ULINUX not permitted for open source distributions; ULINUX disabled ***" >& 2
     ULINUX=0
 fi
 
@@ -214,14 +186,17 @@ set_ulinux_pf()
     PF_MAJOR=1
     PF_MINOR=0
     PF_DISTRO=ULINUX
-    PF_DISTRO_ULINUX_D=`[ -e /usr/bin/dpkg ] && echo 1`
-    if [ -n "$PF_DISTRO_ULINUX_D" ]; then
-        PF_DISTOR_ULINUX_R=
+
+    if [ -e /usr/bin/dpkg ]; then
         BUILD_DPKG=1
         PKG_SUFFIX=deb
     else
-        PF_DISTRO_ULINUX_R=`[ -e /usr/bin/rpmbuild ] && echo 1`
-        BUILD_RPM=1
+        if [ -e /usr/bin/rpmbuild ]; then
+            BUILD_RPM=1
+        else
+            echo "Can't determine if this system should build .DEB or .RPM packages" >& 2
+            exit 1
+        fi
     fi
 }
 
@@ -255,6 +230,17 @@ case $uname in
             PF_MAJOR=`head -n 1 /etc/redhat-release | sed 's/.* \([0-9][0-9]*\)[ \.].*/\1/'`
             PF_MINOR=`(head -n 1 /etc/redhat-release | sed 's/.* [0-9][0-9]*[\.]\([0-9][0-9]*\).*/\1/') | grep -v '[^0-9]' || echo '0'`
             PF_DISTRO=REDHAT
+        elif [ -n "$CHECK_CENTOS" ]; then
+            PF_MAJOR=`head -n 1 /etc/redhat-release | sed 's/.* \([0-9][0-9]*\)[ \.].*/\1/'`
+            PF_MINOR=`(head -n 1 /etc/redhat-release | sed 's/.* [0-9][0-9]*[\.]\([0-9][0-9]*\).*/\1/') | grep -v '[^0-9]' || echo '0'`
+            if [ $PF_MAJOR -eq 5 -a $PF_MINOR -eq 0 ]; then
+                set_ulinux_pf
+                BUILD_RPM=1
+                BUILD_DPKG=1
+                ULINUX=1
+            else
+                PF_DISTRO=REDHAT
+            fi
         elif [ -e /etc/lsb-release ]; then
             source /etc/lsb-release
             if [ "$DISTRIB_ID" = "Ubuntu" ]; then
